"""Phase P3: the committee note is deterministic and complete without any model; Terra
prose is optional for two sections, every generated sentence is tied to the verified facts
or excluded as UNSUPPORTED; one demo-wide budget cap."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from radar.config import CONFIG_DIR, load_rules, load_settings
from radar.db import Database
from radar.llm.pricing import Pricing
from radar.llm.provider import ExtractionRequest, ExtractionResponse, LLMProvider, estimate_tokens
from radar.notes import build_note, render_markdown
from radar.notes.llm import GenerationLedger, NoteProse, generate_prose
from radar.notes.model import CommitteeNote, verify_claim
from tests.test_alerts import fallen_angel


@pytest.fixture(scope="module")
def rules():
    return load_rules(CONFIG_DIR / "rules.yaml")


@pytest.fixture(scope="module")
def settings():
    return load_settings(CONFIG_DIR / "settings.yaml")


def test_the_deterministic_note_is_complete_in_both_languages(rules, scales, settings):
    alert = fallen_angel(rules, scales, settings.alerts)
    fr = build_note(alert, "fr")
    en = build_note(alert, "en")
    for note in (fr, en):
        assert isinstance(note, CommitteeNote) and note.priority == "P1"
        assert [f.index for f in note.key_facts] == [1, 2] and note.key_facts[0].source == 1
        assert [r.id for r in note.triggered_rules] == ["RAT-01", "RAT-02"]
        assert note.why_it_matters.source == "deterministic"
        assert [c.status for c in note.why_it_matters.claims] == ["VERIFIED", "VERIFIED"]
        assert note.points_to_verify.claims and note.points_to_verify.source == "deterministic"
        assert note.verification == {
            "verified": len(note.why_it_matters.claims) + len(note.points_to_verify.claims),
            "partial": 0,
            "unsupported": 0,
        }
        assert note.unsupported == [] and note.model_provenance is None
        assert note.sources[0].raw_sha256 == "7" * 64
    md_fr, md_en = render_markdown(fr), render_markdown(en)
    assert (
        md_fr.startswith("# NOTE DE COMITÉ DE CRÉDIT")
        and "Émetteur" in md_fr
        and "Aucune recommandation d'investissement" in md_fr
    )
    assert (
        md_en.startswith("# CREDIT COMMITTEE NOTE")
        and "Why it matters" in md_en
        and "No investment recommendation" in md_en
    )
    assert "S&P Global Ratings downgrade: BBB- → BB+, IG → HY" in md_en
    assert "[1]" in md_en and "7" * 64 in md_en and "Unsupported claims: 0" in md_en
    assert "RAT-01" in md_en and "RAT-02" in md_en
    assert "generated by" not in md_en.lower() or "to be validated by the analyst" in md_en


def test_every_generated_sentence_is_tied_to_the_facts_or_excluded(rules, scales, settings):
    alert = fallen_angel(rules, scales, settings.alerts)
    prose = NoteProse(
        why_it_matters=[
            "S&P moved the rating from BBB- to BB+, below investment grade [1].",
            "The downgrade follows a 12% fall in revenue [1].",
            "Moody's and Fitch kept the issuer investment grade.",
            "The agency cited a weaker outlook [9].",
        ],
        points_to_verify=["Confirm the outlook stable after the action [1][2]."],
    )
    note = build_note(alert, "en", prose=prose)
    assert note.why_it_matters.source == "llm"
    body = [c.text for c in note.why_it_matters.claims]
    assert body == ["S&P moved the rating from BBB- to BB+, below investment grade [1]."]
    annex = {c.text: c for c in note.unsupported}
    assert set(annex) == {
        "The downgrade follows a 12% fall in revenue [1].",
        "Moody's and Fitch kept the issuer investment grade.",
        "The agency cited a weaker outlook [9].",
    }
    assert (
        annex["The downgrade follows a 12% fall in revenue [1]."].checks["numbers_consistent"]
        is False
    )
    assert (
        annex["Moody's and Fitch kept the issuer investment grade."].checks["citation_present"]
        is False
    )
    assert annex["The agency cited a weaker outlook [9]."].checks["passage_found"] is False
    assert note.verification == {"verified": 2, "partial": 0, "unsupported": 3}
    md = render_markdown(note)
    body, annex = md.split("## Annex")
    assert "12% fall" not in body and "[9]" not in body and "kept the issuer" not in body
    assert "12% fall" in annex and "Unsupported claims: 3" in md
    assert "excluded from the committee note" in annex


def test_verify_claim_checks_are_deterministic_and_explicit(rules, scales, settings):
    alert = fallen_angel(rules, scales, settings.alerts)
    ok = verify_claim("The rating went from BBB- to BB+ [1].", alert.facts)
    assert ok.status == "VERIFIED" and ok.citations == [1]
    bad = verify_claim("Leverage reached 4.5x [1].", alert.facts)
    assert bad.status == "UNSUPPORTED" and "4.5" in (bad.reason or "")


class ProseProvider(LLMProvider):
    name = "openai"

    def __init__(self) -> None:
        self.calls = 0

    def complete(self, request: ExtractionRequest) -> ExtractionResponse:
        self.calls += 1
        assert "[1]" in request.user and "RAT-01" in request.user
        raw = json.dumps(
            {
                "why_it_matters": ["The issuer lost its investment grade rating at S&P [1]."],
                "points_to_verify": ["Check whether Moody's or Fitch announce a review [1]."],
            }
        )
        return ExtractionResponse(
            raw_json=raw, model_id=request.model_id, resolved_model=request.model_id, provider=self.name,
            input_tokens=request.estimated_input_tokens, output_tokens=estimate_tokens(raw), latency_ms=3,
            reasoning_effort=request.reasoning_effort,
        )  # fmt: skip


def _pricing() -> Pricing:
    return Pricing.model_validate(
        {
            "version": "t",
            "models": {
                "gpt-5.6-terra": {"input_per_million_usd": 2.0, "output_per_million_usd": 12.0}
            },
        }
    )


def test_prose_is_generated_once_under_the_demo_cap_and_recorded(
    tmp_path: Path, rules, scales, settings
):
    alert = fallen_angel(rules, scales, settings.alerts)
    db = Database(tmp_path / "r.db")
    db.init_schema()
    ledger = GenerationLedger(tmp_path / "ledger.json", cap_usd=1.0)
    provider = ProseProvider()
    first = generate_prose(
        db,
        alert,
        "en",
        provider=provider,
        pricing=_pricing(),
        ledger=ledger,
        model_id="gpt-5.6-terra",
    )
    assert first.prose is not None and first.cost_usd is not None and 0 < first.cost_usd < 0.05
    assert provider.calls == 1 and ledger.spent_usd == first.cost_usd and ledger.remaining_usd < 1.0
    second = generate_prose(
        db,
        alert,
        "en",
        provider=provider,
        pricing=_pricing(),
        ledger=ledger,
        model_id="gpt-5.6-terra",
    )
    assert second.prose == first.prose and second.cost_usd == 0.0 and provider.calls == 1  # cached
    note = build_note(alert, "en", prose=first.prose, provenance=first.provenance)
    assert (
        note.model_provenance is not None and note.model_provenance["model_id"] == "gpt-5.6-terra"
    )
    assert [c.status for c in note.why_it_matters.claims] == ["VERIFIED"]
    saved = json.loads((tmp_path / "ledger.json").read_text())
    assert saved["cap_usd"] == 1.0 and len(saved["entries"]) == 1
    db.close()


def test_prose_is_refused_without_a_call_when_the_cap_is_spent(
    tmp_path: Path, rules, scales, settings
):
    alert = fallen_angel(rules, scales, settings.alerts)
    db = Database(tmp_path / "r.db")
    db.init_schema()
    ledger = GenerationLedger(tmp_path / "ledger.json", cap_usd=1.0)
    ledger.record("other", "fr", 1.0, "gpt-5.6-terra")
    provider = ProseProvider()
    result = generate_prose(
        db,
        alert,
        "en",
        provider=provider,
        pricing=_pricing(),
        ledger=ledger,
        model_id="gpt-5.6-terra",
    )
    assert (
        result.prose is None and provider.calls == 0 and "budget" in (result.reason or "").lower()
    )
    note = build_note(alert, "en", prose=None, notice=result.reason)
    assert note.why_it_matters.source == "deterministic" and result.reason in render_markdown(note)
    db.close()


def test_a_french_decimal_comma_matches_the_filing_figure(rules, scales, settings):
    """6,6 in a French sentence is the 6.6 of the English filing; 7,6 is not."""
    from radar.alerts.model import AlertFact

    fact = AlertFact(
        index=1, text="As of June 30, 2026, we had $6.6 million in cash and a working capital deficit of $108.1 million.",
        field="flag:liquidity", source=1, doc_id="d", char_start=0, char_end=10, evidence_type="llm_statement",
        extractor_version="x",
    )  # fmt: skip
    ok = verify_claim(
        "La trésorerie s'élève à 6,6 millions de dollars pour un déficit de 108,1 millions [1].",
        [fact],
    )
    assert ok.status == "VERIFIED"
    bad = verify_claim("La trésorerie s'élève à 7,6 millions de dollars [1].", [fact])
    assert bad.status == "UNSUPPORTED" and "7,6" in (bad.reason or "")
